id = "cache_ttl"
weight = 1
type = "snippet"
title = "Cache TTL and Custom Keys"
description = "Determine how/if Cloudflare's [Classic CDN](/about/using-cache.md#cloudflare-s-cdn) and Browsers will cache a resource by setting TTLs, cache keys, and cache settings."

[demos.main]
text = "Demo"
url = "https://cloudflareworkers.com/#8dd3e29985701b05e43b4dd74c387b74:https://example.com/"
tags = [ "Middleware", "Enterprise" ]
